### ISSUE TITLE
mapbox-owners

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/cz-mapbox-changelog#1]
@tmcw mapbox-owners is failing to add people to this npm package.

![image](https://cloud.githubusercontent.com/assets/1551510/10590195/6c7dc926-767d-11e5-9ea2-eca7e523fc94.png)

Any idea why this might be happening?

https://www.npmjs.com/package/cz-mapbox-changelog

**Comment by tmcw** [comment]
Does `npm owner add lyzidiamond cz-mapbox-changelog` work? All the tool does is [shell out](https://github.com/mapbox/mapbox-owners/blob/master/mapbox-owners#L21)

**Comment by mcwhittemore** [comment]
Gotcha. It was a logging in problem. I'll open a PR for mapbox-owners to show the npm error.
